# Generated by Django 5.2.6 on 2025-11-29 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="QUIZ",
            new_name="quiz",
        ),
    ]
